name: chefie
description: "Aplicativo de recomendação de receitas baseado em ingredientes"

publish_to: 'none' #

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  
  # Gerenciamento de Estado
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.5.0
  
  # Backend
  supabase_flutter: ^2.5.0
  
  # HTTP e Imagens
  http: ^1.2.0
  cached_network_image: ^3.3.1
  
  # Armazenamento Local (Recurso Extra)
  shared_preferences: ^2.2.2
  
  # Cupertino Icons
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  riverpod_generator: ^2.5.0
  build_runner: ^2.4.8
  custom_lint: ^0.7.6
  riverpod_lint: ^2.3.0

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: PlusJakartaSans
      fonts:
        - asset: fonts/PlusJakartaSans-ExtraBold.ttf
          weight: 800
        - asset: fonts/PlusJakartaSans-Bold.ttf
          weight: 700
        - asset: fonts/PlusJakartaSans-SemiBold.ttf
          weight: 600
        - asset: fonts/PlusJakartaSans-Medium.ttf
          weight: 500
        - asset: fonts/PlusJakartaSans-Regular.ttf
          weight: 400
        - asset: fonts/PlusJakartaSans-Light.ttf
          weight: 300
        - asset: fonts/PlusJakartaSans-ExtraLight.ttf
          weight: 200
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
